### ISSUE TITLE
Version 0.3.0

### ISSUE THREAD

**Issue by dfurmans** [sbt/sbt-cucumber#18]
Is the new version already available ? 
We have try to bump it but end up with the error
```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.waioeka.sbt#cucumber-plugin;0.3.0: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
```
related to the [commit](https://github.com/sbt/sbt-cucumber/commit/a991ae2603dc9d3774b2ee4201b7436c5ffd1f4a) made by @gedeh 
 
thanks in advance !

**Comment by dfurmans** [comment]
Is already there :tada: 
https://search.maven.org/artifact/com.waioeka.sbt/cucumber-plugin/0.3.0/jar

**Comment by lewismj** [comment]
Published a new version. Will update to Scala 3 hopefully this week and tidy up etc.
